### ISSUE TITLE
Greenkeeper needs to be reinitialized

### ISSUE THREAD

**Issue by rockchalkwushock** [microauth/microauth-vkontakte#8]
- [x] I have searched the [issues]() of this repository and believe that this is not a duplicate.

## Expected Behavior

On dependency & dev-dependency SemVer updates Greenkeeper should open PR's alerting dev team of changes to critical dependencies of package.

## Current Behavior

I believe the GreenKeeper is still linked to the old repository ownership of `rockchalkwushock/microauth-vkontakte` and it will need to be reinitialized.

Just cloning the package and running a `yarn outdated` showed that 2 dependencies are behind on patches & feature upgrades:

```sh
rockchalkwushock in microauth-vkontakte on next $ yarn outdated
yarn outdated v1.1.0
Package                Current Wanted Latest Package Type    URL                                                        
all-contributors-cli   4.4.0   4.4.0  4.5.0  devDependencies https://github.com/jfmengels/all-contributors-cli#readme   
eslint                 4.5.0   4.5.0  4.7.2  devDependencies http://eslint.org                                          
eslint-config-prettier 2.3.0   2.3.0  2.6.0  devDependencies https://github.com/prettier/eslint-config-prettier#readme  
jest                   20.0.4  20.0.4 21.2.0 devDependencies http://facebook.github.io/jest/                            
lint-staged            4.0.4   4.0.4  4.2.3  devDependencies https://github.com/okonet/lint-staged#readme               
nsp                    2.7.0   2.7.0  2.8.1  devDependencies https://github.com/nodesecurity/nsp#readme                 
prettier               1.6.1   1.6.1  1.7.0  devDependencies https://prettier.io                                        
request                2.81.0  2.81.0 2.83.0 dependencies    https://github.com/request/request#readme                  
request-promise        4.2.1   4.2.2  4.2.2  dependencies    https://github.com/request/request-promise#readme          
semantic-release       7.0.2   7.0.2  8.0.3  devDependencies https://github.com/semantic-release/semantic-release#readme
✨  Done in 0.85s.
```

## Steps to be taken:

@dimapaloskin 

I'm not sure if I have the permissions to reinitialize greenkeeper on the repository. This is the [link](https://greenkeeper.io/docs#installation) for the installation instructions for the repository. I won't update and push the updates so once greenkeeper is back to tracking the repository it will manage all of this and we can roll the PR's into a `next` branch.

**Comment by dimapaloskin** [comment]
@rockchalkwushock done :) See initial PR from the greenkeeper
